server:
  port: 8091
spring:
  application:
    name: spring-bops
http:
    multipart:
      maxFileSize: 51MB
      maxRequestSize: 51MB
multipart:
  maxFileSize: 51MB
  maxRequestSize: 51MB
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
ribbon:
  ConnectTimeout: 30000
  ReadTimeout: 600000
  ServerListRefreshInterval: 3000      
hystrix: 
  command: 
    default: 
      execution: 
        isolation: 
          thread: 
            timeoutInMilliseconds: 6000          